### ISSUE TITLE
Красивый шаблон нашего сайта (статический, просто html файлы)

### ISSUE THREAD

**Issue by Evgeniy-02** [and-se/NmMap#1]

**Comment by and-se** [comment]
Нужно доработать предоставленный шаблон:

1) Фоновая картинка - выровнять по центру и возможно растянуть по ширине
2) Попробовать убрать подчёркивание букв в алфавите
3) Разобраться с подключением нестандартных шрифтов - не надо надеяться на то, что на компютере пользователя шрифт стоит, а надо предоставлять его как external font.
4) Сделать страницу жизнеописания. Всего нужно 3 страницы: главная, буква А, жизнеописание.

**Comment by and-se** [comment]
ждём новостей. В некотором виде уже присоединили шаблон к приложению.

**Comment by and-se** [comment]
Надо посмотреть и присоединить последний шаблон от Ксюши

**Comment by Evgeniy-02** [comment]
1.Картинку растянул по ширине, сделал отступы 5 px справа и слева
2. Убрал подчеркивания в алфавите
3. Подключил шрифты. Папка со шрифтами /NmMap/src/main/resources/static/fonts
3.1 Вынес стили и подлючение шрифтов в css файл. Теперь они доступны /NmMap/src/main/resources/static/styles
ea5325e0df98399df75c0ef08085cfd0b2a855fe

@KseniaTya (Ксюша), осталось сделать 4 пункт.
Пункт 5: Исправить таблицу, сдалать красивой)) Текущий вид можно увидеть в файле 
[изображение](https://user-images.githubusercontent.com/61192625/83941934-e5a86300-a7f7-11ea-8c9b-c48958cd2e9d.png)
