### ISSUE TITLE
Внятная подпись к точкам на карте

### ISSUE THREAD

**Issue by and-se** [and-se/NmMap#15]
Надо подумать, что мы показываем при клике на точку карты.
Например:
ФИО (она же ссылка на жизнеописание) + датировка и текст события

**Comment by Evgeniy-02** [comment]
На элементарном уровне точка на карте имеет описание и ссылку на жизнеописание человека.
d5335e346c81768884c6dfa1242a123616f3a338

**Comment by and-se** [comment]
Также @Theonefeo добавил даты событий.
