### ISSUE TITLE
Неправильная выборка для буквы С

### ISSUE THREAD

**Issue by and-se** [and-se/NmMap#22]
При выборе данных на букву С выбираются жизнеописания, начинающиеся со "Священномученик" (при этом в самом ФИО ничего на С может и не начинаться). А нам надо отбирать данные по ФИО - чин святости в реквизит ФИО не входит.

**Comment by Svjatoslav-so** [comment]
Исправленно в коммите 569d2008172e87561b59f83c695737238a194d04
