### ISSUE TITLE
Рядом стоящие точки схлопывать в одну

### ISSUE THREAD

**Issue by and-se** [and-se/NmMap#29]

**Comment by and-se** [comment]
В рамках одного события бывает несколько вариантов координат, но на очень небольшом расстоянии. Скорее всего это связано с тем, что при встрече одного и того же названия исследователь выбирал точку на карте внутри одного и того же населённого пункта - но каждый раз немного разную.
Так что такие точки надо схлопыать в одну - на уровне конвертера. Пока в рамках одного события.

**Comment by and-se** [comment]
За меру расстояния, внутри которого можно схлопывать, можно взять 1 км.

**Comment by and-se** [comment]
Расстояние между точками считать Евклидово на плоскости. Конечны есть формулы для вычисления расстояния между точками на сфероиде, но у нас такие масштабы, что можно считать плоскостью.

**Comment by Evgeniy-02** [comment]
> В рамках одного события бывает несколько вариантов координат, но на очень небольшом расстоянии. Скорее всего это связано с тем, что при встрече одного и того же названия исследователь выбирал точку на карте внутри одного и того же населённого пункта - но каждый раз немного разную.
> Так что такие точки надо схлопыать в одну - на уровне конвертера. Пока в рамках одного события.

Как должно улучшение быть связано с кластерами, которые автоматически создает Я.Карта? Оно будет заменять кластеризацию?

**Comment by and-se** [comment]
Думаю, пока никак. Всё равно при увеличении масштаба до полной карты мира в кластер будут схлопываться несколько точек про разные события одного человека - и ФИО в списке будет повторяться несколько раз.

Данная задача про другое - встречаются случаи, когда у одного события несколько точек, стоящих совсем недалеко друг от друга. И уже при небольшом увеличении масштаба начинаются повторы ФИО в кластеризаторе.
