### ISSUE TITLE
Фильтрация меток на карте по интервалу времени

### ISSUE THREAD

**Issue by and-se** [and-se/NmMap#31]
В интерфейс основной карты нужно добавить возможность фильтрации точек по интервалу времени.

С датами событий у нас всё сложно:
* у некоторых есть только год
* у некоторых - год и месяц
* а некоторые вообще звучат как "1950-е"
* у других же вообще нет даты (хотя они могут находиться между двумя событиями, у которых дата есть)
* а у третих прописано несколько вариантов даты

На первое время можно сделать фильтрацию только по годам. "1950-е" можно расценивать как любой год от 1950 до 1959.
Рекомендуется во входных данных посмотреть на массив Поисковые_даты.

**Comment by and-se** [comment]
Нужно, чтобы после конвертации у каждой метки была информация хотя бы о годах - т.е. интервал от Год_начала и Год_окончания.
Для этого из входных данных можно брать интервал лет из первого элемента массива События[].Поисковые_даты[]

**Comment by Evgeniy-02** [comment]
77c3de405fe03a6fc736ab2a3646a8cb00806652

**Comment by Evgeniy-02** [comment]
77c3de405fe03a6fc736ab2a3646a8cb00806652
