### ISSUE TITLE
Добавить подкрашивание меток в соответствии с их типом (создать эту типизацию)

### ISSUE THREAD

**Issue by Svjatoslav-so** [and-se/NmMap#33]
К примеру, можно разбить на категории: метки касающиеся рождения,  метки касающиеся кончины, метки о всем остальном. Из "о всем остальном"  можно выделить ещё. И подкрасить каждый тип своим цветом.

**Comment by and-se** [comment]
План предварительного исследования:
* Построить список уникальных типов событий, которые упоминаются в файлах из resources/input по пути События[].Тип.
  Для этого можно воспользоваться кодом конвертера данных

* Типы событий надо протащить через конвертер, чтобы в программе также для каждого события (ну или метки на карте) хранился его тип.
* Подумать, на какие 3-5 групп мы распределим события, придумать цвета для этих групп.

**Comment by Evgeniy-02** [comment]
Задача решена d870072cd618d70e71a170b09ef3309960af687f
