### ISSUE TITLE
Уточнение поиска по ФИО

### ISSUE THREAD

**Issue by and-se** [and-se/NmMap#39]
Сейчас при поиске по ФИО мы можем задать только первую букву для поиска, а дальше придётся пролистывать результаты постранично (ну или бинарным поиском по номерам страниц).

Для удобства поиска по ФИО надо дать возможность задавать и следующие буквы.
Тут возможны 2 варианта - дать текстовое поле для ввода искомого ФИО, либо прорисовывать возможные вторые буквы: "выбрали А, нам нарисовали кнопки Аа Аб Ав....".

Максимальная степень развития обоих вариантов есть в [БД За Христа пострадавшие](http://martyrs.pstbi.ru/bin/code.exe/frames/m/ind_oem.html/charset/ans) - поиск по ФИО там очень хорошо проработан.

В нашей системе предлагаю поступить по варианту один (он проще в реализации) - после выбора буквы из алфавита на появившейся странице списка жизнеописаний надо добавить текстовое для уточнения искомого ФИО.

Кстати говоря, можно как-то предусмотреть возможность поиска не только по началу ФИО (starts-with), но и в любом месте (contains) - ведь наш MtStorage поддерживает оба варианта поиска. Например по такому правилу:
* просто слово - ищем по началу строки
* слово, обрамлённое "*" - поиск по подстроке.
* возможна комбинация вида Иван \*Иванов\* - ищем строки вида "Иван ..... Иванов .....".
// т.е. "*" означает любое количество любых символов, в частности пустую строку.

**Comment by Svjatoslav-so** [comment]
Исправлено в коммитах:
01b9ac1586abd86b0c6e4f02f4c279b7452a9ca2 (Добавлено текстовое поле для поиска по ФИО)
0aaee55205afbd9c2627ffdb1e08f920179384c5 ( В поиске по ФИО добавили возможность поиска по подстроке)

**Comment by and-se** [comment]
* Есть баг: ищем **по подстроке** "Иван".
* Переходим на вторую страницу результатов
--> слетает настройка "по подстроке" - ищется "с начала строки".

**Comment by Svjatoslav-so** [comment]
Исправлено в коммите:
2894a217237b73eebb65a6bfe8aceb601f86cfeb
