### ISSUE TITLE
Каким образом мы будем отдавать метки для отрисовки в карту (ведь карта - это по сути пользователь нашего сайта).

### ISSUE THREAD

**Issue by Evgeniy-02** [and-se/NmMap#4]

**Comment by and-se** [comment]
Сейчас по запросу map/all_points просто отдаются все точки в виде JSON.
На больших объёмах данных вряд ли будет адекватно работать.

**Comment by and-se** [comment]
На данный момент вся фильтрация идёт на стороне браузера в java script.

**Comment by and-se** [comment]
Пока отдаём сразу все точки (около 3500 точек). Работает нормально, на смартфонах тоже.
