### ISSUE TITLE
Скорость загрузки и работы карты на полной БД

### ISSUE THREAD

**Issue by and-se** [and-se/NmMap#47]
Надо пробовать ObjectManager и прочее в соответствии со статьёй https://habr.com/ru/company/yandex/blog/243665/

**Comment by and-se** [comment]
Долго загружается карта. Попробовать LocalObjectManager - это потребует работы на стороне сервера - см #4

**Comment by Evgeniy-02** [comment]
Достаточно ли  ObjectManager'а, который сейчас испльзуется, или разбираться с LocalObjectManager?

**Comment by and-se** [comment]
Пока достаточно ObjectManager-а, пусть он и грузит сразу все метки.
Также несколько помогает включённое вчера gzip-сжатие трафика, так что все точки передаются в виде сжатых 400 кб, а не 3.2 мб как ранее.
