### ISSUE TITLE
Улучшение полнотекстового поиска - пояснительные тексты в результатах и сортировка по степени полезности

### ISSUE THREAD

**Issue by Evgeniy-02** [and-se/NmMap#5]

**Comment by and-se** [comment]
Хотим добиться следующего:
* В результатах поиска помимо ФИО надо выводить кусочек текста жизнеописания, который объясняет совпадение (см. яндекс или google).
* сортировать результаты по степени релевантности (возьмём степень близости икомых слов).

Зарубки есть в 30d102381b350f69d803674857280f63887bde2d
Нужно доработать класс TextSearchImage в соответствии с комментариями

**Comment by and-se** [comment]
Сегодня  @AnastasiiaRumak  реализовала 9939ef59bb6b11cdc6a614a3907c4c4113e89627  улучшенный полнотекстовый поиск в ветке fts - он упорядочивает результаты поиска по релевантности (в нашем случае степени близости искомых слов в тексте, а при поиске одного слова - степени близости слова к началу текста), а также помимо ссылки на жизнеописание выдаёт кусочек текста из него, в котором находится совпадение с запросом (подсветка искомых слов пока не сделана).

Кусочек текста мы пытаемся выбрать так, чтобы его начало и конец были началом и концом предложения. Для этого ориентируемся на знаки препинания ".!?".

Но проблема в том, что в тексте есть сокращения наподобие "родился в с. Ивановка", так что мы выделяем предложение "родился в с.", что не очень логично. Также в тексте не всегда корректные предложения, например:
```
ИВАНОВ Иван Иванович
1870 - родился в с.Ивановка.
```

При поиске "родился" кусочект текста с совпадением будет такой:

```
"ИВАНОВ Иван Иванович 1870 - родился в с"
```

Посему предлагаю следующие доработки класса TextSearchImage:
* в методе getTextSnippet в качестве знаков окончания предложения взять "!?.\n"
* добавить перегрузку getTextSnippet(int maxLength, String sentenceSeparator), куда пользователь может передать свои символы которые следует считать окончанием предложения.
_(В java нет параметров по умолчанию, так что добавляем перегрузку метода)_


На наших данных (жизнеписания) мы можем заметить, что события отделяются друг от друга \n. Логично в тексте с совпадением взять события целиком. Посему в MtSimpleStorage.findHumansFullText надо вызывать TextSearchImage.getTextSnippet с передачей sentenceSeparator = "\n".
NB! Мы добавляем перегрузку getTextSnippet, а не просто модифицируем имеющийся метод для того, чтобы TextSearchImage не был завязан на структуру наших данных и мы могли бы его использовать в дальнейшем для других целей.

**Comment by and-se** [comment]
@AnastasiiaRumak внесла итоговую версию коммитом df860afad3b9010e0de622f70f60f980025737e8.
