### ISSUE TITLE
Постраничная выдача данных

### ISSUE THREAD

**Issue by and-se** [and-se/NmMap#7]
Список жизнеописаний (в частности при поиске) может быть достаточно длинным. Не нужно выводить все данные сразу.

Список надо разбить на страницы по 20 записей и показывать за один раз только одну страницу, а после списка поставить ссылки на предыдующую и следующую страницы.

Для этого:
1) В запросы /persons и /search надо добавить необязательный параметр page, по умолчанию page=1.
2) В view после вывода списка жизнеописаний надо добавить панель навигации со ссылками "назад", "вперёд". Эти ссылки ведут на тот же адрес, но только с другим значением параметра page (на единицу меньше или больше).

**Comment by Evgeniy-02** [comment]
>В view после вывода списка жизнеописаний надо добавить панель навигации со ссылками "назад", "вперёд"
Как сделать такие кнопки я еще не разобрался

Кроме вышеописанного, задачу выполнил eedac0f41bd6a47d55a053ab7d47d1f251bdc778
